# Generated by Django 3.1.5 on 2021-01-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='age',
            new_name='age_1',
        ),
    ]
